nelmio_api_doc:
    documentation:
        info:
            title: 'Library Management System API'
            description: 'This is API documentation for Library Management System.'
            version: '1.0.0'
    areas:
        default:
            path_patterns: ['^/api(?!/doc$)']
